services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  rate-limiter:
    container_name: rate-limiter
    build:
      context: ./
    environment:
      - TOKEN=TokenTest
    ports:
      - "8080:8080"
    depends_on:
      - redis
